### ISSUE TITLE
this script can be used in production environment?

### ISSUE THREAD

**Issue by andreabisello** [stayallive/pingdom-to-cachet#7]
we want to migrate from statuspage to cachethq.
statuspage have integration with pingdom.
this script was released 3 years ago, someone can give me an updated feedback?
thakns

**Comment by stayallive** [comment]
I would assume it is really broken, I believe Pingdom (maybe even Cahet too) has since even updated their API and deprecated the one I'm using here.

You are free to take/fork the code and adapt it to the new API.

I will archive this repository later today indicating it is no longer maintained (I am no longer running this and also no longer using Pingdom, now on [Nixstats](http://nixstats.com/) and [Oh Dear!](https://ohdear.app/) which both have status pages)!

**Comment by andreabisello** [comment]
@stayallive  thanks.
